### PR TITLE
Review PR #110 

### PR DESCRIPTION
**Pull request by jibeee**
Minor changes related to PR #110.

- "view_tag" and "view_tag_full" are now properly escaped in documentation.
- I modified the prototype of `monero_derive_view_tag` for readability.

This app has a lot of legacy code, I think new code should have better standards than the older one.

### CODE REVIEW

**Review by fbeutin-ledger — APPROVED** [review]

**Comment by fbeutin-ledger** [comment]
There is indeed a lot of legacy code
There is a follow-up ticket on our board to implement the testing CI for all devices
The static analysis tools added should really help see code smells quickly and I think a good goal would be to require better standard for all new code and modified code

**Comment by fbeutin-ledger** [comment]
Does it seems sufficient measures for you ?

**Comment by fbeutin-ledger** [comment]
Or we can add a task to cleanup Monero, after all it's an in-house app so latest code standards should be expected

**Comment by jibeee** [comment]
> Does it seem sufficient for you ?

Yes, what I mean is that it is a common (and good) practice for contributors to follow the coding style of a project.

But for that specific app, it looks outdated to me, and I think new contributions could use a better coding style than the current one.

**Pull request merged**
