### PR TITLE
Add support of CLSAG signature algorithm

### PR DESCRIPTION
**Pull request by grydz**
The Monero blockchain will change the signature algorithm from MLSAG to CLSAG in the next hardforks (v13 and v14). This PR adds necessary changes in the Monero app to interact with the future release of the Monero client `0.17.0.0`:

- Add support of CLSAG signature (`INS_CLSAG`)
- Update to protocol v4 for support of both MLSAG and CLSAG
- Update InProofv1 to InProofv2

### CODE REVIEW

**Comment by selsta** [comment]
Any estimate when CLSAG / v0.17 supporting version will be released? We plan to release v0.17 on 2020-09-17, it would be good to have the update available until then.

**Comment by selsta** [comment]
ping @grydz, when will the app be available? We will release v0.17 today.

**Comment by FabriceDautriat** [comment]
@selsta The Monero-dev app is available once you enable the **developer mode** in Ledger Live settings.

The version of the app is v1.7.0.

image


As soon as the Monero GUI is released, the public Monero app will be updated to 1.6.0.

Please make sure to ping me when it's the case 🙏

**Comment by selsta** [comment]
Thank you for the update, I will comment once the GUI is released :)

**Comment by selsta** [comment]
FWIW I tested it on testnet and it did not seem to work.

```
[wallet 9tEZdz]: transfer 9tRKWiE3nuo5izj2FUZuAVeVpCdbT1j3i8YKMCWShip5aFsa5As12S42UrcPwYtKHDKxBF3jcjh8CYE8VkrHgpncEDqDxw5 0.5
Wallet password: 

Transaction 1/1:
Spending from address index 0
Sending 0.500000000000.  The transaction fee is 0.000031710000

Is this okay?  (Y/Yes/N/No): y
Error: transaction <43edfe6407ffe442d6cbfaa3a0b8ffb3d47b2f53cfaaa4ab63d8dcfe0c258d43> was rejected by daemon
Error: Reason: invalid input
```

On the daemon side:

```
2020-09-18 12:11:05.015	D Using 0.000000021939/byte fee
2020-09-18 12:11:05.015	D Mixin: 10-10
2020-09-18 12:11:05.016	D Device 0 Created
2020-09-18 12:11:05.025	I verRctMGSimple/verRctCLSAGSimple failed for input 0
2020-09-18 12:11:05.025	E Failed to check ringct signatures!
2020-09-18 12:11:05.026	I tx used wrong inputs, rejected
2020-09-18 12:11:05.026	E Transaction verification failed: <96c5d81bb05796fd2a5f26ef0301bcd7e3042cbb2cdc5321d660a2a9e1db573d>
2020-09-18 12:11:05.026	W [on_send_raw_tx]: tx verification failed: invalid input
```

Will test on stagenet now.

**Comment by selsta** [comment]
Stagenet and mainnet still seem to work fine so there is a bit of time to get this issue resolved.

**Comment by grydz** [comment]
Monero application 1.7.1 is available and should fix the problem.

**Comment by grydz** [comment]
Well, Monero application 1.7.2 should fix the problem!

**Comment by selsta** [comment]
@grydz v0.17 GUI is now released.

**Comment by grydz** [comment]
> @grydz v0.17 GUI is now released.

Alright, I'm merging the PR.

**Pull request merged**
